# Generated by Django 3.1.3 on 2020-12-08 16:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('owner', models.CharField(max_length=32)),
                ('estimated_time', models.PositiveIntegerField(default=0)),
                ('time_worked', models.FloatField(default=0)),
                ('time_left', models.FloatField(default=0)),
            ],
        ),
    ]
